# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: MoreUnit Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        targetplatform: [eclipse-4.22, eclipse-4.24]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Get Time for BUILD_ID
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDD_HHmm'
          
      - name: Get Branch name for BUILD_LABEL
        id: branch_name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        
      - name: Set up Java ☕️
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'


      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Build Everything
        env:
          BUILD_ID: "${{ steps.time.outputs.time }}"
          BUILD_TYPE: "S"
          BUILD_LABEL: "CI ${{ steps.time.outputs.time }} (${{ steps.branch_name.outputs.branch }})"
        run: xvfb-run mvn -file org.moreunit.build/pom.xml verify -Dtarget.platform.classifier=${{ matrix.targetplatform }}  --fail-at-end -Dtycho.disableP2Mirrors=true --batch-mode --strict-checksums --update-snapshots -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: Publish Surefire Test Results for  🖨
        if: ${{ always() }}
        uses: ScaCap/action-surefire-report@v1
        with:
          check_name: Test Results for ${{ matrix.targetplatform }} 

